---
abstract: 'Fast and lightweight Perl client for Riak'
author:
  - 'Tiago Peczenyj <tiago.peczenyj@gmail.com>'
  - 'Damien Krotkine <dams@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0
  Test::MockModule: 0
  Test::MockObject: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Riak-Light
recommends:
  JSON::XS: 0
requires:
  Carp: 0
  Const::Fast: 0
  Google::ProtocolBuffers: 0
  JSON: 0
  Moo: 0
  Time::Out: 0
  Type::Params: 0
  Types::Standard: 0
  perl: 5.012
resources:
  bugtracker: https://github.com/Weborama/Riak-Light/issues
  homepage: https://github.com/Weborama/Riak-Light
  repository: git://github.com///github.com/Weborama/Riak-Light.git
version: 0.073
